server {
    listen 80;
    server_name 38.180.131.172;

    location /static/ {
        alias /var/www/Flarken-2.0/flarken/staticfiles/;
    }

    location / {
        proxy_pass http://127.0.0.1:8000;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
    }
}