server {
    listen 80;
    server_name _;  # замінити на свій домен або IP

    # Static files (Django Admin, Jazzmin)
    location /static/ {
        alias /staticfiles/;
    }

    # Django Admin і API
    location / {
        proxy_pass http://web:8000;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
    }
}